name: Generate 3D Contribution Graph (Night-Rainbow)

on:
  schedule:
    - cron: '0 0 * * *'      # her gün
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build graph
        uses: yoshi389111/github-profile-3d-contrib@v2      # <-- DÜZELTİLDİ
        with:
          username: furkanhanilci
          output: ./profile-3d-contrib/night-rainbow.png
          config: night-rainbow

      - name: Commit & push image
        uses: EndBug/add-and-commit@v9
        with:
          add: profile-3d-contrib/night-rainbow.png
          message: "Update night-rainbow contribution graph"
